# Generated by Django 6.0.3 on 2026-03-13 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Diary",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(help_text="Введите заголовок", max_length=200, verbose_name="Заголовок")),
                (
                    "content",
                    models.TextField(blank=True, help_text="Введите запись", null=True, verbose_name="Запись"),
                ),
                (
                    "publication_date",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Введите дату записи", verbose_name="Дата записи"
                    ),
                ),
            ],
            options={
                "verbose_name": "запись",
                "verbose_name_plural": "записи",
                "ordering": ["-publication_date"],
            },
        ),
    ]
