# Generated by Django 6.0.3 on 2026-03-13 09:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("diary", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="diary",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="Введите автора",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="diary",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор",
            ),
        ),
    ]
